### ISSUE TITLE
{{{flash}}} layout usage in ejs template

### ISSUE THREAD

**Issue by dewelloper** [RGBboy/express-flash#10]
how can i add the body flash in ejs

<<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    {{{flash}}}
</body>
</html>

in my case layout like below

<!DOCTYPE html>
<html lang="en">
<head>

<script type="jscript" src='/javascripts/jquery.min.js'></script>
<link rel="stylesheet" type="text/css" href='/stylesheets/style.css'>
<link rel="stylesheet" type="text/css" href='/stylesheets/bootstrap.min.css'>

</head>
<body>
    <% include partials/head.ejs %>   
    <% include partials/header.ejs %>
    <div class="container">
        <div class="starter-template">
            <%- body %>
        </div>
    </div>
    <% include partials/footer.ejs %>
</body>

</html>

please help me

**Comment by derekahmedzai** [comment]
You can add them in an ejs template like this
```
<% if (messages.info) { %>
  <%= messages.info %>
<% } %>
```

**Comment by k4dm3l** [comment]
Hi, actually im doing this:

```
router.post("/", (req, res) => {
 
    req.flash('info', 'You Must click on captcha');

    return res.json({
      success: false,
      msg: "You Must click on captcha"
    });
  }
```

And in my html i have this, but dont works and i really dont know whats happen, can you help me??

```
<div class="messages">
     <span><%= messages.info %></span>
</div>
```
