### ISSUE TITLE
Doesn't work with redis?

### ISSUE THREAD

**Issue by matthew-dean** [RGBboy/express-flash#2]
When using redis sessions (connect-redis), I get the error "req.flash() requires sessions".

Any recommendations?

**Comment by RGBboy** [comment]
The error is created by the underlying library `connect-flash`. You can read about the requirements of connect flash [here](https://github.com/jaredhanson/connect-flash). Essentially the request object needs to have a session property. This can be added by using the `express-session` middleware.

If you could post the code that you use to set up redis and your sessions perhaps I could see where it is not working.
