### ISSUE TITLE
Option to change the local identifier

### ISSUE THREAD

**Issue by samholmes** [RGBboy/express-flash#3]
Is there an option to customize what the identifier is for the local; instead of `messages`. Also, why wouldn't something like `flash` be the default? That would seem to make more sense.

**Comment by RGBboy** [comment]
express-flash is just a wrapper around [connect-flash](https://github.com/jaredhanson/connect-flash) that adds the ability to define a flash message and render it without redirecting the request. If connect flash allows it then we could add an option argument to pass on to connect-flash. Looking at the current version of connect-flash, they do not support this option so you would need to request a change there.

**Comment by RGBboy** [comment]
Sorry, my mistake, connect-flash doesn't concern itself with the res.locals object at all. I'll have a look into how we can best do this.

**Comment by RGBboy** [comment]
I just looked into this further and the latest version of connect-flash now supports the feature I was trying to add. I would suggest you just use connect-flash. You can specify what view local you want the flash message to be attached to when you render:

``` javascript
app.get('/flash', function(req, res){
  req.flash('info', 'Flash is back!')
  res.render('index', { messages: req.flash('info') });
});
```
